### PR TITLE
Allow docker to access host devices

### PR DESCRIPTION
**Pull request by tspmelo**
This will allow the dashboard to list devices and display its smartctl data.

Signed-off-by: Tiago Melo <tmelo@suse.com>

### CODE REVIEW

**Comment by p-se** [comment]
lgtm. this will enable `device management` but to be able to display smartctl data you'll also need to have `smartmontools >= 7.0.0`.

**Comment by tspmelo** [comment]
Done.

**Comment by ricardoasmarques** [comment]
@tspmelo please rebase

**Comment by tspmelo** [comment]
Done

**Pull request merged**
